spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/goorm_db
    username: goorm-board
    password: goorm1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  thymeleaf:
    cache: false

  messages:
    basename: messages/ValidationMessages
    encoding: UTF-8

logging:
  level:
    org.thymeleaf: DEBUG
    web: DEBUG