spring:
  profiles:
    active: mybatis  # 기본 프로파일은 JPA 사용

  # 공통 데이터소스 설정
  datasource:
    url: jdbc:mariadb://localhost:3307/task
    username: task
    password: 1234

  # 공통 Thymeleaf 설정
  thymeleaf:
    cache: false

  # 공통 Flyway 설정
  flyway:
    locations: classpath:db/migration/maria
    baseline-on-migrate: true
    validate-on-migrate: false
    repair-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    ignore-missing-migrations: true
    ignore-future-migrations: true
    ignore-ignored-migrations: true
    ignore-pending-migrations: true
    out-of-order: true

# 공통 로깅 설정
logging:
  level:
    org.springframework.security: DEBUG
    io.goorm.board.service.UserService: DEBUG
    io.goorm.board.controller.AuthController: DEBUG
    org.springframework.security.authentication: TRACE
    org.springframework.security.web: TRACE
  charset:
    console: UTF-8
    file: UTF-8