spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/goorm_db
    username: goorm-board
    password: goorm1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true


  thymeleaf:
    cache: false

  messages:
    basename: messages/validation/ValidationMessages,messages/i18n/messages
    encoding: UTF-8

logging:
  level:
    org.springframework.security: DEBUG
    io.goorm.board.service.UserService: DEBUG
    io.goorm.board.controller.AuthController: DEBUG
    org.springframework.security.authentication: TRACE
    org.springframework.security.web: TRACE
  charset:
    console: UTF-8
    file: UTF-8