spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mariadb://localhost:3307/goorm_db
    username: goorm-board
    password: goorm1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  thymeleaf:
    cache: false